positive:
i am running pyspark unit tests cases using gitlabci/cd pipeline and i am getting the above error, below is the content under test stage of my gitlabci.yml:- .
locally all works but inside the gitlab-runner (gitlabci) all falied because this: .
negative:
i was facing the same issue with gitlabci, changing maven image from /code_segment/ to /code_segment/ seems to fix the issue.
is a multiline script block in a gitlabci pipeline immediately aborted if a call within these instructions returns an exit code that is not equal to zero?
